name: ${{ values.app_name }}-cicd

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'

permissions:
  contents: write

jobs:
  ci:
    runs-on: ubuntu-latest

    outputs:
      commit_id: ${{ '${{ steps.vars.outputs.commit_id }}' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ '${{ secrets.DOCKERHUB_USERNAME }}' }}
          password: ${{ '${{ secrets.DOCKERHUB_TOKEN }}' }}

      - name: Set short SHA
        id: vars
        shell: bash
        run: |
          echo "commit_id=${GITHUB_SHA::6}" >> $GITHUB_OUTPUT
          echo "Generated commit_id=${GITHUB_SHA::6}"

      - name: Debug commit_id
        run: |
          echo "commit_id=${{ '${{ steps.vars.outputs.commit_id }}' }}"

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: alipendix/${{ values.app_name }}:${{ '${{ steps.vars.outputs.commit_id }}' }}

  cd:
    runs-on: self-hosted
    needs: ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug commit_id
        run: |
          echo "commit_id=${{ '${{ needs.ci.outputs.commit_id }}' }}"

      - name: Install yq
        run: |
          curl -L \
            https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 \
            -o yq

          chmod +x yq
          sudo mv yq /usr/local/bin/yq

      - name: Modify values file
        run: |
          COMMIT_ID="${{ '${{ needs.ci.outputs.commit_id }}' }}"

          echo "Using image tag: $COMMIT_ID"

          yq -i ".image.tag = \"$COMMIT_ID\"" \
            charts/${{ values.app_name }}/values-${{ values.app_env }}.yaml

          cat charts/${{ values.app_name }}/values-${{ values.app_env }}.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update image tag to ${{ '${{ needs.ci.outputs.commit_id }}' }}"

      - name: Install ArgoCD CLI
        shell: bash
        run: |
          curl -sSL -o argocd \
            https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64

          chmod +x argocd
          sudo mv argocd /usr/local/bin/

          argocd version --client

      - name: ArgoCD app sync
        shell: bash
        run: |
         echo "Syncing ArgoCD application..."
         argocd login argocd-server.argocd.svc.cluster.local \
         --insecure \
         --grpc-web \
         --username admin \
         --password ${{ '${{ secrets.ARGOCD_PASSWORD }}' }}


      - name: Ensure ArgoCD repo app
        shell: bash
        run: | 
          repo="https://github.com/alleraro-org/${{ values.app_name }}.git"
          argocd repo list | grep -q $repo || argocd repo add $repo

          argocd app get ${{ values.app_name }} || argocd app create ${{ values.app_name }} \
            --repo $repo \
            --path charts/${{ values.app_name }} \
            --dest-server https://kubernetes.default.svc \
            --dest-namespace ${{ values.app_env }} \
            --values values-${{ values.app_env }}.yaml \
            --revision main \
            --sync-policy manual \
            --sync-option CreateNamespace=true
                
      - name: ArgoCD app sync
        shell: bash
        run: |
          echo "Syncing ArgoCD application..."
          
          argocd app sync ${{ values.app_name }}
          argocd app wait ${{ values.app_name }} --timeout 180
